// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc948.NRGRobot2013.subsystems;

import edu.wpi.first.wpilibj.AnalogChannel;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc948.NRGRobot2013.RobotMap;

/**
 * @author Patrick & Charles
 */
public class DiscMagazine extends Subsystem {

    private int count = 0;
    private Relay magPiston = RobotMap.magPiston;
    private AnalogChannel IRSensor = new AnalogChannel(3);
    private static final double THRESHOLD = .1;
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    public void openPiston() {
        magPiston.set(Relay.Value.kReverse);
    }

    public void closePiston() {
        magPiston.set(Relay.Value.kOff);
        count++;
    }

    public int getCount() {
        return count;
    }
    
    public double getVoltage()
    {
        if ( IRSensor != null)
        {
            return IRSensor.getAverageVoltage();
        }
        SmartDashboard.putNumber("Voltage: ", getVoltage());
        return 0;
    }
    public boolean frisbeeLoaded()
    {
         
         return getVoltage() < THRESHOLD;         
    }
}
